# automation_registry.py

AUTOMATIONS = [

    # ========================================================
    # 1. CHECKEM
    # ========================================================

    {
        "id": "checkem",
        "name": "Checkem",
        "category": "URL & Campaign",
        "status": "Production",

        "description": (
            "Takes URLs containing UTM parameters and validates "
            "them for potential UTM syntax issues."
        ),

        "use_when": [
            "The user wants to validate UTM parameters",
            "The user wants to check URLs for UTM syntax issues",
            "The user has a list of campaign URLs that need validation",
            "The user wants to identify malformed UTM parameters"
        ],

        "input": [
            "URLs containing UTM parameters"
        ],

        "output": [
            "UTM validation results"
        ],

        "scope": "General",

        "tags": [
            "UTM",
            "URL",
            "Campaign",
            "Validation"
        ],

        "page": "pages/Checkem.py"
    },


    # ========================================================
    # 2. GA4 REQUEST PARAMETER BREAKDOWN
    # ========================================================

    {
        "id": "ga4_request_parameter_breakdown",
        "name": "GA4 Request Parameter Breakdown",
        "category": "GA4",
        "status": "Production",

        "description": (
            "Takes GA4 network requests and breaks them down "
            "into their individual parameters. Requests are "
            "grouped by event name and the results can be "
            "downloaded as an Excel file."
        ),

        "use_when": [
            "The user has GA4 network requests",
            "The user wants to analyse GA4 request parameters",
            "The user wants to see parameters grouped by event name",
            "The user wants an Excel breakdown of GA4 requests",
            "The user wants to inspect GA4 event parameters"
        ],

        "input": [
            "GA4 network requests"
        ],

        "output": [
            "Parameter breakdown",
            "Excel file"
        ],

        "scope": "General",

        "tags": [
            "GA4",
            "Network Requests",
            "Parameters",
            "Events",
            "Excel",
            "Analysis"
        ],

        "page": "pages/GA4_Request_Parameter_Breakdown.py"
    },


    # ========================================================
    # 3. GTM SNIPPET IDENTIFIER
    # ========================================================

    {
        "id": "gtm_snippet_identifier",
        "name": "GTM Snippet Identifier",
        "category": "GTM",
        "status": "Production",

        "description": (
            "Takes website URLs, visits the websites and "
            "scrapes the HTML to identify the GTM snippet ID "
            "present on the page."
        ),

        "use_when": [
            "The user wants to identify a GTM container ID",
            "The user wants to check whether a GTM snippet exists",
            "The user wants to identify GTM snippets across websites",
            "The user has multiple Commercial Lubes website URLs"
        ],

        "input": [
            "Website URLs"
        ],

        "output": [
            "GTM snippet ID"
        ],

        "scope": "Commercial Lubes",

        "tags": [
            "GTM",
            "Snippet",
            "Container",
            "HTML",
            "Scraping"
        ],

        "page": "pages/GTM_Snippet_Identifier.py"
    },


    # ========================================================
    # 4. GTM QA AUTOMATION
    # ========================================================

    {
        "id": "gtm_qa_automation",
        "name": "GTM QA Automation",
        "category": "GTM / GA4 QA",
        "status": "Work in Progress",

        "description": (
            "Takes a text file containing HTML IDs. The filename "
            "represents the webpage URL. The automation reconstructs "
            "the URL from the filename, visits the website, simulates "
            "click interactions for each supplied HTML ID and captures "
            "the resulting GA4 network requests. Results can be "
            "downloaded as a JSON file."
        ),

        "use_when": [
            "The user wants to automate GTM QA",
            "The user wants to test website elements automatically",
            "The user wants to simulate clicks on HTML elements",
            "The user wants to capture GA4 requests generated by clicks",
            "The user has a text file containing HTML IDs",
            "The user wants to perform repeated interaction-based QA"
        ],

        "input": [
            "Text file containing HTML IDs",
            "The filename encodes the webpage URL"
        ],

        "output": [
            "GA4 network requests",
            "QA results",
            "JSON file"
        ],

        "scope": "General",

        "tags": [
            "GTM",
            "GA4",
            "QA",
            "HTML",
            "Playwright",
            "Network Requests"
        ],

        "dependencies": [
            "HTML ID Extractor can be used to generate the required HTML ID files"
        ],

        "page": "pages/GTM_QA_Automation_v2_(WIP).py"
    },


    # ========================================================
    # 5. HTML ID EXTRACTOR
    # ========================================================

    {
        "id": "html_id_extractor",
        "name": "HTML ID Extractor",
        "category": "Web / QA Preparation",
        "status": "Production",

        "description": (
            "Takes multiple website URLs, visits each website and "
            "scrapes the HTML to identify all element IDs beginning "
            "with 'link_'. A separate text file is generated for "
            "each website containing the extracted IDs."
        ),

        "use_when": [
            "The user wants to extract HTML IDs from websites",
            "The user wants to find IDs beginning with link_",
            "The user wants to prepare input files for GTM QA Automation",
            "The user wants to identify clickable link elements",
            "The user has multiple website URLs that need HTML ID extraction"
        ],

        "input": [
            "Website URLs"
        ],

        "output": [
            "One text file per website",
            "Each text file contains the extracted link_ HTML IDs"
        ],

        "scope": "General",

        "tags": [
            "HTML",
            "IDs",
            "Web Scraping",
            "QA",
            "GTM",
            "link_"
        ],

        "feeds_into": [
            "gtm_qa_automation"
        ],

        "page": "pages/HTML_ID_Extractor.py"
    },


    # ========================================================
    # 6. JSON TO TEXT
    # ========================================================

    {
        "id": "json_to_text",
        "name": "JSON → Text",
        "category": "Data & Files",
        "status": "Production",

        "description": (
            "Takes a JSON file containing GA4 requests and "
            "extracts the GA4 requests into a text file. "
            "Each GA4 request is placed on a separate line. "
            "The resulting text file can be used as input for "
            "the GA4 Request Parameter Breakdown automation."
        ),

        "use_when": [
            "The user has GA4 requests stored in JSON",
            "The user wants to convert JSON GA4 output to text",
            "The user wants one GA4 request per line",
            "The user wants to prepare a file for GA4 Request Parameter Breakdown"
        ],

        "input": [
            "JSON file containing GA4 requests"
        ],

        "output": [
            "TXT file",
            "One GA4 request per line"
        ],

        "scope": "General",

        "tags": [
            "JSON",
            "GA4",
            "Text",
            "Conversion",
            "Data Preparation"
        ],

        "feeds_into": [
            "ga4_request_parameter_breakdown"
        ],

        "page": "pages/JSON_To_Text.py"
    },


    # ========================================================
    # 7. ONETRUST MODAL IDENTIFIER
    # ========================================================

    {
        "id": "onetrust_modal_identifier",
        "name": "OneTrust Modal Identifier",
        "category": "OneTrust",
        "status": "Production",

        "description": (
            "Takes multiple website URLs, visits the websites "
            "and scrapes their HTML to identify the OneTrust "
            "snippet ID."
        ),

        "use_when": [
            "The user wants to identify a OneTrust snippet ID",
            "The user wants to check OneTrust implementation",
            "The user wants to identify OneTrust IDs across websites",
            "The user has multiple URLs requiring OneTrust identification"
        ],

        "input": [
            "Website URLs"
        ],

        "output": [
            "OneTrust snippet ID"
        ],

        "scope": "Project-specific",

        "tags": [
            "OneTrust",
            "Consent",
            "Snippet",
            "HTML",
            "Scraping"
        ],

        "page": "pages/OneTrust_Modal_Identifier.py"
    },


    # ========================================================
    # 8. ONETRUST QA
    # ========================================================

    {
        "id": "onetrust_qa",
        "name": "OneTrust QA",
        "category": "OneTrust",
        "status": "Work in Progress",

        "description": (
            "Runs an automated OneTrust QA scenario. The automation "
            "visits a webpage, checks the current consent value, "
            "allows consent to be changed and checks whether "
            "tracking tags or network requests fire according "
            "to the consent state."
        ),

        "use_when": [
            "The user wants to QA OneTrust consent",
            "The user wants to test cookie consent behaviour",
            "The user wants to change consent and observe tracking",
            "The user wants to check whether tags fire after consent changes",
            "The user wants to validate OneTrust implementation"
        ],

        "input": [
            "Website URL"
        ],

        "output": [
            "OneTrust consent results",
            "Tag firing results",
            "QA results"
        ],

        "scope": "Project-specific",

        "tags": [
            "OneTrust",
            "Consent",
            "QA",
            "Tags",
            "GA4",
            "Network Requests"
        ],

        "page": "pages/OneTrust_QA_(WIP).py"
    }
]